apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.vs.name }}
  namespace: {{ .Values.vs.namespace }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ .Values.gw.namespace }}/{{ .Values.gw.name }}
  http:
    - match:
        - uri:
            prefix: "/eu"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: {{ .Values.vs.host }}
            port:
              number: {{ .Values.vs.portNumber }}
    - match:
        - uri:
            prefix: "/de"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: {{ .Values.vs.host }}
            port:
              number:  {{ .Values.vs.portNumber }}
            subset: {{ .Values.vs.subsetDE }}
    - match:
        - uri:
            prefix: "/fr"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: {{ .Values.vs.host }}
            port:
              number: {{ .Values.vs.portNumber }}
            subset: {{ .Values.vs.subsetFR }}
    - match:
        - uri:
            prefix: "/es"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: {{ .Values.vs.host }}
            port:
              number: {{ .Values.vs.portNumber }}
            subset: {{ .Values.vs.subsetES }}
