apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ing.name }}
  namespace: {{ .Values.ing.namespace }}
  annotations:
    "service.beta.kubernetes.io/aws-load-balancer-internal": "true"
  labels:
    app: {{ .Values.ing.app }}
    istio: {{ .Values.ing.istio }}
    release: istio
    istio.io/rev: default
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "IngressGateways"
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.ing.app }}
    istio: {{ .Values.ing.istio }}
  ports:
    - name: {{ .Values.ing.portName }}
      port: {{ .Values.ing.portNumber }}
      protocol: {{ .Values.ing.protocol }}
      targetPort: {{ .Values.ing.targetPort }}
